q()
knitr::opts_chunk$set(echo = TRUE)
db <- read.csv(file="data.csv", header = TRUE, sep = ";")
db <- read.csv (file="data.csv", header = TRUE, sep = ";")
db <- read.csv (file = "data.csv", header = TRUE, sep = ";")
db <- read.csv (file = "analyse 1.csv", header = TRUE, sep = ";")
knitr::opts_chunk$set(echo = TRUE)
db <- read.csv(file="data.csv", header = TRUE, sep = ";")
db
knitr::opts_chunk$set(echo = TRUE)
db <- read.csv(file="analyse 1.csv", header = TRUE, sep = ";")
db <- read.csv(file="analyse 1.csv", header = TRUE, sep = ";")
db <- read.csv(file="analyse 1.csv", header = TRUE, sep = ";")
db <- read.csv(file="analyse 1.csv", header = TRUE, sep = ";")
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
x<-c(10, 15, 20, 25)
y<-c(1, 2, 3, 4)
db <- data.frame(x,y)
db
db <- read.csv(file="data.csv", header = TRUE, sep = ";")
db
list.(analyse)
db <- read.csv("analyse.csv", header = TRUE, sep = ";")
getwd()
setwd("c:/Users/DORIAN/Desktop/DEBUT R")
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
setwd("c:/Users/DORIAN/Bureau/DEBUT R")
setwd("c:/Users/DORIAN/Ce PC/Bureau/DEBUT R")
setwd("c:/Users/DORIAN/Ce PC\Bureau/DEBUT R")
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
db
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
db
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
view(db)
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
View(db)
knitr::opts_chunk$set(echo = TRUE)
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
View(db)
# chargement du fichier .csv dans R
knitr::opts_chunk$set(echo = TRUE)
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
View(db)
head(analyse)
getwd()
head(analyse.csv)
analyse
head(data)
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
View(db)
head(data)
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
View(db)
head(data)
mean(data$Age)
mean(analyse$Age)
mean(data$Age)
mean(db$Age)
table(db$sexe)
table(db$maladie)
table(db$sexe)
barplot(table(db$sexe), col = c("red","skyblue"))
table(db$maladie)
barplot(db$maladie), col("green", "yellow"))
table(db$maladie)
barplot(db$maladie), col = c("green", "yellow"))
table(db$maladie)
barplot(db$maladie), col=c("green", "yellow"))
table(db$maladie)
barplot(table(db$maladie), col=c("green", "yellow"))
table(db$sexe)
barplot(table(db$sexe), col = c("red","skyblue"))
hist(db$Age)
hist(db$Age)
hist(db$)
hist(db$Age)
hist(db$Age, xlap="Age")
hist(db$Age)
hist(db$Age, Agelap="Age")
main ="histgramme"
hist(db$Age)
plot(db$Age, Agelap="Ages")
hist(db$Age, main="distribution des Ages", xlap="Age")
hist(db$Age, main="distribution des Ages", db$Agelap="Age")
table(db$sexe, db$maladie)
hist(db$Age, main="distribution des Ages", col=c("green","red"))
hist(db$Age, main="distribution des Ages", col="lightblue")
table(db$sexe, db$maladie)
hist(db$Age, main="distribution des Ages", col="lightblue", xlab = "ages des participants",)
hist(db$Age, main="distribution des Ages", col="lightblue", xlab = "ages des participants",)
table(db$maladie)
barplot(table(db$maladie), col=c("green", "yellow"))
table(db$sexe)
barplot(table(db$sexe), col = c("red","skyblue"))
table(db$maladie)
table(db$sexe)
mean(db$Age)
head(data)
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
View(db)
db <- read.csv(file="analyse.csv", header = TRUE, sep = ";")
db
